---
apiVersion: v1
kind: Service
metadata:
  name: apicast
  namespace: guidewire-infra
  labels:
    app: apicast
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: apicast
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: proxy
    - port: 8090
      targetPort: 8090
      protocol: TCP
      name: management
  type: ClusterIP
