apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: guidewire-apps
  labels:
    app: customers-service
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: customers-service
  ports:
    - name: http
      port: 8085
      targetPort: 8085
      protocol: TCP
  type: ClusterIP
