apiVersion: apps/v1
kind: Deployment
metadata:
  name: drools-engine
  namespace: guidewire-apps
  labels:
    app: drools-engine
    app.kubernetes.io/part-of: guidewire-poc
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: drools-engine
  template:
    metadata:
      labels:
        app: drools-engine
        app.kubernetes.io/part-of: guidewire-poc
    spec:
      containers:
        - name: drools-engine
          image: image-registry.openshift-image-registry.svc:5000/guidewire-apps/drools-engine:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              protocol: TCP
          env:
            - name: DB_URL
              value: "jdbc:postgresql://postgres.guidewire-infra.svc.cluster.local:5432/drools_audit"
            - name: DB_USERNAME
              value: "drools_user"
            - name: DB_PASSWORD
              value: "drools123"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8086
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8086
            initialDelaySeconds: 15
            periodSeconds: 5
            failureThreshold: 3
