apiVersion: v1
kind: Service
metadata:
  name: drools-engine
  namespace: guidewire-apps
  labels:
    app: drools-engine
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: drools-engine
  ports:
    - name: http
      port: 8086
      targetPort: 8086
      protocol: TCP
  type: ClusterIP
