apiVersion: v1
kind: Service
metadata:
  name: incidents-service
  namespace: guidewire-apps
  labels:
    app: incidents-service
    app.kubernetes.io/part-of: guidewire-poc
spec:
  selector:
    app: incidents-service
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
  type: ClusterIP
